#include <diffusionworks/engines/black_scholes_analytic.hpp>

#include <nlohmann/json.hpp>

#include <gtest/gtest.h>

#include <cmath>
#include <filesystem>
#include <fstream>
#include <string>

namespace diffusionworks {
namespace {

// ---------------------------------------------------------------------------
// Validation against an independent high-precision oracle.
//
// Why this exists alongside the Richardson consistency tests
// ----------------------------------------------------------
// Differencing the engine's own price proves that its Greeks are the derivatives
// of its price, and nothing more. A fault shared by both -- a wrong price formula
// with a consistently wrong delta -- survives that check. It cannot be the
// oracle.
//
// This fixture is independent of the C++ engine in both directions:
//
//   - the price is computed by a separate implementation (mpmath), so a wrong
//     C++ price formula is caught;
//   - each Greek is obtained by differentiating that price at 50 decimal digits
//     rather than by evaluating a closed form, so a wrong C++ Greek formula is
//     caught even if it is consistently wrong.
//
// The reference file is generated by python/generate_bs_references.py and
// committed under data/references/. Python is external analysis here (ADR-002):
// it produces a fixed, versioned fixture and never runs as part of the engine.
//
// Together with the published Hull and Haug values -- a human-checked source
// independent of any code -- no single oracle is load-bearing.
//
// Tolerances
// ----------
// The reference carries ~25 significant digits, so its own error is
// irrelevant here; what is being measured is the double-precision engine. The
// bound is therefore set by double's ~1e-16 relative resolution, allowed a
// margin for accumulated rounding across the handful of exp, log, and erfc calls
// in each formula. An absolute floor accompanies the relative term because
// several references are legitimately near zero (deep out-of-the-money delta and
// gamma), where a relative bound has no meaning.
// ---------------------------------------------------------------------------

class HighPrecisionReferenceTest : public ::testing::Test {
protected:
    static void SetUpTestSuite() {
        const std::filesystem::path path =
            std::filesystem::path(DW_TEST_DATA_DIR) / "references" / "black_scholes.json";

        std::ifstream stream(path);
        ASSERT_TRUE(stream.is_open())
            << "reference fixture not found: " << path
            << "\nregenerate with: python3 python/generate_bs_references.py > "
               "data/references/black_scholes.json";

        ASSERT_NO_THROW(document_ = nlohmann::json::parse(stream));
        ASSERT_TRUE(document_.contains("cases"));
        ASSERT_FALSE(document_["cases"].empty());
    }

    /// Parses a reference written with more digits than a double can hold.
    /// std::stod rounds correctly to nearest, which is exactly what is wanted:
    /// the comparison is against the closest double to the true value.
    static double reference(const nlohmann::json& value) {
        return std::stod(value.get<std::string>());
    }

    static void expect_close(double actual,
                             double expected,
                             double rel_tolerance,
                             double abs_tolerance,
                             const std::string& what) {
        const double allowed = abs_tolerance + rel_tolerance * std::abs(expected);
        EXPECT_NEAR(actual, expected, allowed)
            << what << "\n  engine    : " << actual << "\n  reference : " << expected
            << "\n  allowed   : " << allowed;
    }

    static nlohmann::json document_;
};

nlohmann::json HighPrecisionReferenceTest::document_;

// The fixture must state how it was produced, or a future reader cannot judge
// whether it is trustworthy or merely old.
TEST_F(HighPrecisionReferenceTest, FixtureRecordsItsProvenance) {
    ASSERT_TRUE(document_.contains("provenance"));
    const nlohmann::json& provenance = document_["provenance"];

    EXPECT_EQ(provenance["generator"], "python/generate_bs_references.py");
    EXPECT_GE(provenance["mpmath_working_digits"].get<int>(), 30)
        << "reference precision must exceed double's by a wide margin";
    EXPECT_GE(provenance["reported_significant_digits"].get<int>(), 20);
    EXPECT_TRUE(document_.contains("conventions"))
        << "a reference value without its conventions is not usable";
}

TEST_F(HighPrecisionReferenceTest, PricesMatchIndependentImplementation) {
    for (const auto& c : document_["cases"]) {
        const auto market = MarketState::create(c["market"]["spot"].get<double>(),
                                                c["market"]["rate"].get<double>(),
                                                c["market"]["dividend_yield"].get<double>());
        ASSERT_TRUE(market.ok()) << market.error().describe();

        const auto type = parse_option_type(c["option_type"].get<std::string>());
        ASSERT_TRUE(type.has_value());

        const auto option = EuropeanOption::create(*type,
                                                   c["instrument"]["strike"].get<double>(),
                                                   c["instrument"]["maturity"].get<double>());
        ASSERT_TRUE(option.ok()) << option.error().describe();

        const auto model = BlackScholesModel::create(c["model"]["volatility"].get<double>());
        ASSERT_TRUE(model.ok()) << model.error().describe();

        const auto priced =
            BlackScholesAnalyticEngine::price(market.value(), option.value(), model.value());
        ASSERT_TRUE(priced.ok()) << priced.error().describe();

        const std::string what =
            c["scenario"].get<std::string>() + " " + c["option_type"].get<std::string>() + " price";

        // 1e-13 relative is ~1000x double's resolution, which accommodates
        // rounding through the exp/log/erfc chain while remaining far tighter
        // than any real formula error. The 1e-15 floor covers the deep
        // out-of-the-money case, whose price is ~2e-3 but whose terms are ~4e-2.
        expect_close(priced.value().value, reference(c["price"]), 1e-13, 1e-15, what);
    }
}

TEST_F(HighPrecisionReferenceTest, GreeksMatchIndependentImplementation) {
    for (const auto& c : document_["cases"]) {
        const auto market = MarketState::create(c["market"]["spot"].get<double>(),
                                                c["market"]["rate"].get<double>(),
                                                c["market"]["dividend_yield"].get<double>());
        ASSERT_TRUE(market.ok());

        const auto type = parse_option_type(c["option_type"].get<std::string>());
        ASSERT_TRUE(type.has_value());

        const auto option = EuropeanOption::create(*type,
                                                   c["instrument"]["strike"].get<double>(),
                                                   c["instrument"]["maturity"].get<double>());
        ASSERT_TRUE(option.ok());

        const auto model = BlackScholesModel::create(c["model"]["volatility"].get<double>());
        ASSERT_TRUE(model.ok());

        const auto computed =
            BlackScholesAnalyticEngine::greeks(market.value(), option.value(), model.value());
        ASSERT_TRUE(computed.ok()) << computed.error().describe();
        ASSERT_TRUE(computed.value().all_defined())
            << "reference scenarios are all away from the degenerate kink";

        const Greeks& g = computed.value();
        const nlohmann::json& expected = c["greeks"];
        const std::string prefix =
            c["scenario"].get<std::string>() + " " + c["option_type"].get<std::string>() + " ";

        // Absolute floors are set per Greek by the magnitude of the intermediate
        // terms, not of the result: a deep out-of-the-money delta is ~1e-3 but is
        // assembled from terms of order 1, so its achievable absolute accuracy is
        // that of the terms.
        expect_close(*g.delta, reference(expected["delta"]), 1e-12, 1e-15, prefix + "delta");
        expect_close(*g.gamma, reference(expected["gamma"]), 1e-12, 1e-16, prefix + "gamma");
        expect_close(*g.vega, reference(expected["vega"]), 1e-12, 1e-13, prefix + "vega");
        expect_close(*g.theta, reference(expected["theta"]), 1e-12, 1e-13, prefix + "theta");
        expect_close(*g.rho, reference(expected["rho"]), 1e-12, 1e-13, prefix + "rho");
    }
}

// The fixture is only meaningful if it covers the regimes where the formulas are
// hard. A table of at-the-money cases would pass while the tails were wrong.
TEST_F(HighPrecisionReferenceTest, FixtureCoversTheRequiredRegimes) {
    std::vector<std::string> scenarios;
    for (const auto& c : document_["cases"]) {
        scenarios.push_back(c["scenario"].get<std::string>());
    }

    const auto covers = [&](const std::string& name) {
        return std::find(scenarios.begin(), scenarios.end(), name) != scenarios.end();
    };

    // VALIDATION-PLAN section 3: moneyness, maturity, volatility, dividend
    // yield, and rate sign.
    EXPECT_TRUE(covers("at_the_money"));
    EXPECT_TRUE(covers("in_the_money"));
    EXPECT_TRUE(covers("out_of_the_money"));
    EXPECT_TRUE(covers("deep_out_of_the_money"));
    EXPECT_TRUE(covers("deep_in_the_money"));
    EXPECT_TRUE(covers("with_dividend"));
    EXPECT_TRUE(covers("high_dividend"));
    EXPECT_TRUE(covers("low_volatility"));
    EXPECT_TRUE(covers("high_volatility"));
    EXPECT_TRUE(covers("short_dated"));
    EXPECT_TRUE(covers("long_dated"));
    EXPECT_TRUE(covers("negative_rate"));

    // Both option types for every scenario.
    EXPECT_EQ(document_["cases"].size(), 2 * 12);
}

}  // namespace
}  // namespace diffusionworks
