import type { Metadata } from "next";
import { PageHeader } from "@/components/PageHeader";
import { Section } from "@/components/Section";
import { Figure } from "@/components/Figure";
import { DispersionTable } from "@/components/DispersionTable";
import { RelatedExperiments } from "@/components/RelatedExperiments";
import { FIGURE_COPY } from "@/lib/figure-copy";

export const metadata: Metadata = {
  title: "Heston calibration",
  description:
    "Fitting the Heston model to option prices — a controlled test it passes exactly, and a real market that reveals a limit of what the data can determine.",
};

export default function CalibrationPage() {
  return (
    <div className="page">
      <PageHeader
        stage="Heston calibration"
        title="Fitting a model to a market"
        lede="Calibration finds the model parameters that best reproduce a set of observed option prices. Two versions of the exercise are run side by side, and the contrast between them is the finding: one the model recovers perfectly, one it fits well while leaving half its parameters undetermined."
      />

      <Section idx="A" title="The controlled test" id="synthetic">
        <p>
          First, a fair test with a known answer. A set of option prices is manufactured from chosen
          Heston parameters, and the calibration is asked to recover them — starting from a guess
          that deliberately does <em>not</em> begin at the answer. It recovers them essentially
          exactly. This confirms the fitting procedure itself is sound: when the parameters really
          are determined by the data, it finds them.
        </p>
        <Figure
          file="recovery.png"
          alt={FIGURE_COPY["recovery.png"].alt}
          caption={FIGURE_COPY["recovery.png"].caption}
        />
        <RelatedExperiments ids={["EXP-11"]} />
      </Section>

      <Section idx="B" title="A real market" id="market">
        <p>
          Then the same procedure is turned on a real S&amp;P 500 option market — a genuine set of
          quotes across several maturities. To test how stable the result is, the fit is repeated
          seven times under different reasonable choices of starting guess, weighting, and which
          quotes to include. <strong>All seven fit the market well.</strong> A reader stopping there
          would conclude the model was pinned down.
        </p>
        <p>It was not. Look at how much the fitted parameters disagree across those seven fits:</p>
        <DispersionTable />
        <p>
          The parameters controlling near-term behaviour — the correlation and the current
          volatility level — are tightly determined. But mean reversion and the long-run variance
          level swing by more than their own size from one fit to the next. Those two parameters
          trade off against each other in a way this market cannot separate, because a handful of
          maturities carries almost no information about the long run.{" "}
          <strong>A good fit is not the same as a determined model.</strong>
        </p>
        <Figure
          file="parameter-dispersion.png"
          alt={FIGURE_COPY["parameter-dispersion.png"].alt}
          caption={FIGURE_COPY["parameter-dispersion.png"].caption}
        />
      </Section>

      <Section idx="C" title="What the model cannot capture" id="residual">
        <p>
          Because a real market is not generated by the Heston model, the best fit still leaves a
          gap between model and market. That gap is reported strike by strike rather than hidden in
          a single average, so a reader can see where the model tracks the volatility smile and
          where it cannot.
        </p>
        <Figure
          file="residual-surface.png"
          alt={FIGURE_COPY["residual-surface.png"].alt}
          caption={FIGURE_COPY["residual-surface.png"].caption}
        />
        <p>
          This is why the study reports the quality of the fit and the determinacy of the parameters
          as two separate things. Treating a good fit as a determined model would state the part
          that is true and quietly hide the part that matters — which is exactly the caveat this
          study exists to make visible.
        </p>
        <RelatedExperiments ids={["EXP-11", "EXP-12"]} />
      </Section>
    </div>
  );
}
