import type { Metadata } from "next";
import { PageHeader } from "@/components/PageHeader";
import { Section } from "@/components/Section";
import { Figure } from "@/components/Figure";
import { DispersionTable } from "@/components/DispersionTable";
import { RelatedExperiments } from "@/components/RelatedExperiments";
import { FIGURE_COPY } from "@/lib/figure-copy";

export const metadata: Metadata = {
  title: "Calibration & market surface",
  description:
    "A synthetic surface recovered to machine precision, and a real SPY surface that every scenario fits and none identifies.",
};

export default function CalibrationPage() {
  return (
    <div className="page">
      <PageHeader
        stage="Stage 05 — calibration"
        title="Calibration & market surface"
        lede="Two calibration experiments are deliberately paired, and the contrast between them is the finding: a synthetic surface the calibrator recovers exactly, and a real surface it fits well and pins down only in part."
      />

      <Section idx="05.1" title="Synthetic recovery — the control" id="synthetic">
        <p>
          A surface is generated from known Heston parameters, and the calibrator is asked to
          recover them. It does, to near machine precision — and the headline is read from a{" "}
          <strong>blind</strong> start, one that did not begin at the answer. A start seeded at
          the truth recovering the truth would prove nothing about calibration. This is the
          control that shows the optimiser itself is sound.
        </p>
        <Figure
          file="exp11_recovery.png"
          alt={FIGURE_COPY["exp11_recovery.png"].alt}
          caption={FIGURE_COPY["exp11_recovery.png"].caption}
        />
        <RelatedExperiments ids={["EXP-11"]} />
      </Section>

      <Section idx="05.2" title="A real surface, and what it does not determine" id="market">
        <p>
          The same calibrator is pointed at a real SPY option surface with documented
          provenance and timestamp — quotes across three maturities, none excluded by the
          validation filters. Seven scenarios vary the initial guess, the quote weighting, the
          parameter bounds, and the strike/maturity subset. <strong>All seven converge, and all
          seven fit</strong>, with no scenario leaning on a bounds penalty.
        </p>
        <p>
          A reader stopping at the fit quality would conclude the model was pinned down. It is
          not. Across those same scenarios:
        </p>
        <DispersionTable />
        <p>
          The parameters governing the short end are determined by this surface. The pair
          governing the long-run variance level is not: <span className="numeric">κ</span> and{" "}
          <span className="numeric">θ</span> trade off against each other along a valley the
          data does not resolve, because three maturities carry little information about a
          long-run level. <strong>A good fit is not an identified parameter set.</strong>
        </p>
        <Figure
          file="exp12_parameter_dispersion.png"
          alt={FIGURE_COPY["exp12_parameter_dispersion.png"].alt}
          caption={FIGURE_COPY["exp12_parameter_dispersion.png"].caption}
        />
      </Section>

      <Section idx="05.3" title="Model error, reported not hidden" id="residual">
        <p>
          Because a real surface is not generated by Heston, the fit carries genuine model
          error. The engine reports the implied-volatility residual by strike and maturity
          rather than summarising it into a single number, so a reader can see where the model
          tracks the smile and where it cannot.
        </p>
        <Figure
          file="exp12_residual_surface.png"
          alt={FIGURE_COPY["exp12_residual_surface.png"].alt}
          caption={FIGURE_COPY["exp12_residual_surface.png"].caption}
        />
        <p>
          This is why the record keeps objective value, surface fit, parameter dispersion, and
          penalty reliance as four separate findings, and why EXP-12 stands at a warning:
          collapsing them into &ldquo;the calibration converged&rdquo; would state the one that
          is true and hide the one that matters.
        </p>
        <RelatedExperiments ids={["EXP-11", "EXP-12"]} />
      </Section>
    </div>
  );
}
