# Regenerates the git metadata header at build time.
#
# Run as a script (cmake -P) so that the commit hash reflects the tree at build
# time rather than at configure time. The output file is rewritten only when its
# content changes, so an unchanged commit does not force a rebuild.
#
# Required arguments:
#   DW_GIT_OUTPUT  - path of the header to generate
#   DW_SOURCE_DIR  - repository root

find_package(Git QUIET)

set(_git_commit "unknown")
set(_git_commit_short "unknown")
set(_git_dirty "unknown")
set(_git_branch "unknown")

# Runs a git command and returns its trimmed stdout, or "unknown" if git reports
# failure.
#
# Checking the exit code is essential, not defensive: in a repository with no
# commits, `git rev-parse HEAD` writes the literal string "HEAD" to stdout and
# exits 128. Reading stdout alone would stamp every artifact with a commit of
# "HEAD" -- a value that looks like data but identifies nothing.
function(_dw_git_query output_var)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" ${ARGN}
        WORKING_DIRECTORY "${DW_SOURCE_DIR}"
        RESULT_VARIABLE _result
        OUTPUT_VARIABLE _output
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)

    if(NOT _result EQUAL 0 OR _output STREQUAL "")
        set(${output_var} "unknown" PARENT_SCOPE)
    else()
        set(${output_var} "${_output}" PARENT_SCOPE)
    endif()
endfunction()

if(GIT_FOUND AND EXISTS "${DW_SOURCE_DIR}/.git")
    _dw_git_query(_git_commit rev-parse HEAD)
    _dw_git_query(_git_commit_short rev-parse --short HEAD)
    _dw_git_query(_git_branch rev-parse --abbrev-ref HEAD)

    # A dirty working tree invalidates reproducibility claims, so it is recorded
    # explicitly rather than silently ignored.
    #
    # `git status` succeeds with empty output on a clean tree, which is
    # indistinguishable from failure by exit code alone; the result is therefore
    # inspected directly rather than through _dw_git_query.
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${DW_SOURCE_DIR}"
        RESULT_VARIABLE _status_result
        OUTPUT_VARIABLE _git_status
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)

    if(NOT _status_result EQUAL 0)
        set(_git_dirty "unknown")
    elseif(_git_status STREQUAL "")
        set(_git_dirty "false")
    else()
        set(_git_dirty "true")
    endif()
endif()

set(_content "// Generated by cmake/GenerateGitInfo.cmake. Do not edit.
#pragma once

#define DW_GIT_COMMIT \"${_git_commit}\"
#define DW_GIT_COMMIT_SHORT \"${_git_commit_short}\"
#define DW_GIT_BRANCH \"${_git_branch}\"
#define DW_GIT_DIRTY \"${_git_dirty}\"
")

set(_existing "")
if(EXISTS "${DW_GIT_OUTPUT}")
    file(READ "${DW_GIT_OUTPUT}" _existing)
endif()

if(NOT _existing STREQUAL _content)
    get_filename_component(_out_dir "${DW_GIT_OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${_out_dir}")
    file(WRITE "${DW_GIT_OUTPUT}" "${_content}")
    message(STATUS "Updated git metadata: ${_git_commit_short} (dirty=${_git_dirty})")
endif()
